import { Session } from './types';

export const SESSIONS: Session[] = [
  {
    id: 's1',
    title: 'Check in & Networking',
    time: '09:30 AM - 10:00 AM',
    location: 'Lobby / Networking Lounge',
    description: 'Coffee, tea, and networking with fellow Sharif alumni.',
    type: 'social',
    isAfternoon: false,
  },
  {
    id: 's2',
    title: 'Opening Remarks',
    time: '10:00 AM - 10:08 AM',
    location: 'Main Hall',
    description: 'Welcome address by SUTA Leadership.',
    type: 'keynote',
    isAfternoon: false,
  },
  {
    id: 's3',
    title: 'Guest Welcome',
    time: '10:08 AM - 10:15 AM',
    location: 'Main Hall',
    description: 'Welcome by Plug and Play Leadership.',
    type: 'keynote',
    isAfternoon: false,
  },
  {
    id: 's4',
    title: 'Opening Keynote: "The Sharif Impact"',
    time: '10:15 AM - 10:45 AM',
    location: 'Main Hall',
    description: 'Fireside chat with Babak Hodjat focused on his journey and the role of his Sharif education. Conducted by Mohsen Hejrati.',
    type: 'keynote',
    isAfternoon: false,
  },
  {
    id: 's5',
    title: 'History of the University',
    time: '10:45 AM - 11:15 AM',
    location: 'Main Hall',
    description: 'Brief history panel with Dr. Zarghamee, Dr. Partovi, Dr. Nivi, and Ladan Behnia. Moderated by Dr. Tabesh.',
    type: 'workshop',
    isAfternoon: false,
  },
  {
    id: 's6',
    title: 'Professional Development',
    time: '11:15 AM - 12:30 PM',
    location: 'Breakout Rooms',
    description: 'Round table discussions on mentorship, Women in STEM, the future of AI, and Biotechnology. Conducted by Elahe.',
    type: 'workshop',
    isAfternoon: false,
  },
  {
    id: 's7',
    title: 'Networking Lunch',
    time: '12:30 PM - 01:45 PM',
    location: 'Grand Ballroom',
    description: 'Buffet-style lunch and casual networking.',
    type: 'social',
    isAfternoon: false,
  },
  {
    id: 's8',
    title: 'Remembrance',
    time: '01:45 PM - 01:55 PM',
    location: 'Main Hall',
    description: 'Slide show honoring those who are not with us anymore.',
    type: 'social',
    isAfternoon: true,
  },
  {
    id: 's9',
    title: 'Panel: The Next Frontier',
    time: '01:55 PM - 02:55 PM',
    location: 'Main Hall',
    description: 'How Sharif Alumni are Shaping New Technologies. Featuring Nasrin Mostafazdeh, Madison Masaeli, and Mahyar Salek. Moderated by Zahra Hejrati.',
    type: 'workshop',
    isAfternoon: true,
  },
  {
    id: 's10',
    title: 'SUTA History',
    time: '02:55 PM - 03:10 PM',
    location: 'Main Hall',
    description: 'Presentation by Mahshid or Sepideh.',
    type: 'keynote',
    isAfternoon: true,
  },
  {
    id: 's11',
    title: 'Sharing Memories: Open Mic',
    time: '03:10 PM - 03:30 PM',
    location: 'Main Hall',
    description: 'A space for attendees to share their favorite university stories. Hosted by Mansour.',
    type: 'social',
    isAfternoon: true,
  },
  {
    id: 's12',
    title: 'Networking over Tea & Sweets',
    time: '03:30 PM - 04:00 PM',
    location: 'Networking Lounge',
    description: 'Free time to relax or change for the evening formal event.',
    type: 'social',
    isAfternoon: true,
  },
  {
    id: 's13',
    title: '60th Anniversary Gala Dinner',
    time: '06:00 PM - 11:00 PM',
    location: 'Grand Ballroom',
    description: 'Honoring Dr. Tabesh, featuring live performances, DJ music, and dancing.',
    type: 'social',
    isAfternoon: true,
  },
];

export const VENUES = {
  MORNING: {
    name: 'Plug and Play Tech Center',
    address: '440 N Wolfe Rd, Sunnyvale, CA 94085',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Plug+and+Play+Tech+Center+Sunnyvale',
  },
  AFTERNOON: {
    name: 'Santa Clara Marriott',
    address: '2700 Mission College Blvd, Santa Clara, CA 95054',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Santa+Clara+Marriott',
  },
};
